global:
  environment: production
  domain: lawhelp.com

frontend:
  replicaCount: 3
  image:
    repository: lawhelp/frontend
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

apiGateway:
  replicaCount: 2
  image:
    repository: lawhelp/api-gateway
    tag: latest
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi

services:
  auth:
    replicaCount: 2
    image:
      repository: lawhelp/auth-service
      tag: latest
  user:
    replicaCount: 2
    image:
      repository: lawhelp/user-service
      tag: latest
  lawyer:
    replicaCount: 2
    image:
      repository: lawhelp/lawyer-service
      tag: latest
  chat:
    replicaCount: 2
    image:
      repository: lawhelp/chat-service
      tag: latest
  rating:
    replicaCount: 2
    image:
      repository: lawhelp/rating-service
      tag: latest
  ai:
    replicaCount: 2
    image:
      repository: lawhelp/ai-service
      tag: latest

monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true
    adminPassword: changeme

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: www.lawhelp.com
      paths:
        - path: /
          service: frontend
    - host: api.lawhelp.com
      paths:
        - path: /
          service: api-gateway

persistence:
  enabled: true
  storageClass: standard
  size: 10Gi

redis:
  enabled: true
  architecture: replication
  auth:
    enabled: true
    password: changeme

supabase:
  enabled: true
  auth:
    enabled: true
    jwt_secret: changeme
